//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub use super::timeslot::Entity as Timeslot;
// Updated to VenueSeaOrm to not conflict with existing Venue struct
// TODO: rename VenueSeaOrm to Venue
pub use super::venue::Entity as VenueSeaOrm;
