//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "venue")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub description: String,
    pub address: String,
    pub seats: Option<i32>,
    pub published: Option<i8>,
    pub created_at: Option<DateTimeUtc>,
    pub last_modified: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::timeslot::Entity")]
    Timeslot,
}

impl Related<super::timeslot::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Timeslot.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
